site_name: pfSense REST API Guide
repo_url: https://github.com/jaredhendrickson13/pfsense-api
nav:
  - General:
      - Home: index.md
      - Installation & Configuration: INSTALL_AND_CONFIG.md
      - Swagger & OpenAPI: SWAGGER_AND_OPENAPI.md
      - Endpoint Types: ENDPOINT_TYPES.md
      - Authentication & Authorization: AUTHENTICATION_AND_AUTHORIZATION.md
      - Content & Accept Types: CONTENT_AND_ACCEPT_TYPES.md
      - Queries, Filters & Sorting: QUERIES_FILTERS_AND_SORTING.md
      - Working with Object IDs: WORKING_WITH_OBJECT_IDS.md
      - Working with HATEOAS: WORKING_WITH_HATEOAS.md
      - Common Control Parameters: COMMON_CONTROL_PARAMETERS.md
      - GraphQL: GRAPHQL.md
      - Securing API Access: SECURING_API_ACCESS.md
      - Limitations & FAQs: LIMITATIONS_AND_FAQS.md
      - API Reference: https://pfrest.org/api-docs/
  - Advanced Topics:
      - Introduction: ADVANCED_TOPICS_INTRO.md
      - Contributing & Development: CONTRIBUTING.md
      - Security Policy: SECURITY.md
      - Building Custom Authentication: BUILDING_CUSTOM_AUTH_CLASSES.md
      - Building Custom Query Filters: BUILDING_CUSTOM_QUERY_FILTER_CLASSES.md
      - Building Custom Models: BUILDING_CUSTOM_MODEL_CLASSES.md
      - Building Custom Endpoints: BUILDING_CUSTOM_ENDPOINT_CLASSES.md
      - Building Custom Validators: BUILDING_CUSTOM_VALIDATOR_CLASSES.md
      - Building Custom Dispatchers: BUILDING_CUSTOM_DISPATCHER_CLASSES.md
      - Building Custom Caches: BUILDING_CUSTOM_CACHE_CLASSES.md
      - Building Custom Content Handlers: BUILDING_CUSTOM_CONTENT_HANDLER_CLASSES.md
      - Native Schema: NATIVE_SCHEMA.md
      - PHP Reference: https://pfrest.org/php-docs/
theme:
  name: readthedocs
  features:
    - search
    - navigation.tabs
markdown_extensions:
  - admonition
  - codehilite:
      linenums: true
